---
- name: Setup loopback ip
  hosts: all

  tasks:
    - name : Set ip
      ios_l3_interface:
        name: loopback{{item.name}}
        ipv4: "{{item.ipv4}}"
        #ipv4: 10.0.{{item.number}}.1/24
      with_items:
        - {name: 1, ipv4: "10.0.1.1/24"}
        - {name: 2, ipv4: "10.0.2.1/24"}

    - name : Show ip int br
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
